fitnc:
  firebase-admin-key: ${FIREBASE_ADMIN_KEY}
  cors:
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: "Authorization,X-Total-Count,Link,ETag"
    allow-credentials: true
    max-age: 1800
spring:
  profiles:
    active: @active.profile@
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
springdoc:
  api-docs:
    path: /V3/api-docs
